build: update docker with multistage build

diff --git a/services/classification/Dockerfile b/services/classification/Dockerfile
--- a/services/classification/Dockerfile
+++ b/services/classification/Dockerfile
@@ -1,12 +1,45 @@
-# https://hub.docker.com/_/python
-FROM python:3.11-slim-bullseye
+FROM python:3.11-slim as build
 
-WORKDIR /code
+ENV PIP_DEFAULT_TIMEOUT=100 \
+    # Allow statements and log messages to immediately appear
+    PYTHONUNBUFFERED=1 \
+    # disable a pip version check to reduce run-time & log-spam
+    PIP_DISABLE_PIP_VERSION_CHECK=1
 
-COPY ./requirements.txt /code/requirements.txt
+WORKDIR /app
+COPY requirements.txt ./
 
-RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
+RUN pip install --no-cache-dir -r requirements.txt
 
-COPY . /code
+
+### Final stage
+FROM python:3.11-slim as final
+
+WORKDIR /app
+
+COPY --from=build /app/requirements.txt .
+
+RUN set -ex \
+    # Create a non-root user
+    && addgroup --system --gid 1001 appgroup \
+    && adduser --system --uid 1001 --gid 1001 --no-create-home appuser \
+    # Upgrade the package index and install security upgrades
+    && apt-get update \
+    && apt-get upgrade -y \
+    # Install dependencies
+    && pip install -r requirements.txt \
+    # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+
+COPY ./proto proto
+COPY ./service service
+COPY ./main.py .
+
+EXPOSE 50052
 
 CMD ["python", "main.py"]
+
+# Set the user to run the application
+USER appuser
